"""changes relationship between tables

Revision ID: 889a7838120f
Revises: 
Create Date: 2022-04-18 15:19:03.538768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889a7838120f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'item', ['description'])
    op.create_foreign_key(None, 'item', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_column('item', 'owner')
    # ### end Alembic commands ###
